In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
%matplotlib inline

import timeit

rc('font', family='AppleGothic')

plt.rcParams['axes.unicode_minus'] = False

In [35]:
df = pd.read_csv('PCA10.csv')

In [36]:
df = df.drop(columns=['Unnamed: 0'])

In [37]:
df.head()

0         1         2         3         4         5         6  \
0 -2.684460  0.036785  1.879541  0.019208 -0.107785 -0.034836  0.130589   
1 -2.775818  0.093509  2.073433 -0.000016 -0.063533  0.698705 -0.009038   
2 -2.646643  0.028142  1.891135  0.153486 -0.079697 -0.065678  0.075867   
3 -2.947364  0.149220  2.451942 -0.064491  0.052711  2.162850 -0.342604   
4 -2.660183 -0.125432  1.896620 -0.028798 -0.027122 -0.093869 -0.017121   

          7         8         9  label  
0  0.005639  0.780448 -0.096578      1  
1  0.078105 -0.486274  0.179148      1  
2  0.020665  0.745004 -0.179113      1  
3  0.239758 -3.077490  0.675034      1  
4  0.052625  0.701577 -0.297803      1

# Logistic Regression

In [38]:
X = df.drop('label',axis=1).values
y = df['label'].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=101)

In [39]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [40]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()

In [41]:
%%timeit

logmodel.fit(X_train, y_train)

124 ms ± 13.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
predictions = logmodel.predict(X_test)

In [43]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85      3796
           1       0.91      0.89      0.90      5956

    accuracy                           0.88      9752
   macro avg       0.87      0.88      0.88      9752
weighted avg       0.88      0.88      0.88      9752



In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[3298,  498],
       [ 670, 5286]])

# KNN

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()

In [47]:
scaler.fit(df.drop('label',axis=1))

StandardScaler()

In [48]:
scaled_features = scaler.transform(df.drop('label', axis=1))

In [49]:
df_feat = pd.DataFrame(scaled_features, columns=df.columns[:-1])

In [50]:
from sklearn.model_selection import train_test_split
X = df_feat
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
knn = KNeighborsClassifier(n_neighbors=1)

In [53]:
%%timeit

knn.fit(X_train, y_train)

14.4 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [54]:
predictions = knn.predict(X_test)

/opt/homebrew/Caskroom/miniforge/base/envs/jedi/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [55]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[4505   89]
 [ 130 6979]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      4594
           1       0.99      0.98      0.98      7109

    accuracy                           0.98     11703
   macro avg       0.98      0.98      0.98     11703
weighted avg       0.98      0.98      0.98     11703



# Support Vector Machine

In [56]:
from sklearn.model_selection import train_test_split
X = df.drop('label',axis=1)
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [57]:
from sklearn.svm import SVC
svc_model = SVC()

In [58]:
%%timeit

svc_model.fit(X_train,y_train)

4.88 s ± 14.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
predictions = svc_model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[4559  171]
 [ 424 6549]]
              precision    recall  f1-score   support

           0       0.91      0.96      0.94      4730
           1       0.97      0.94      0.96      6973

    accuracy                           0.95     11703
   macro avg       0.94      0.95      0.95     11703
weighted avg       0.95      0.95      0.95     11703

