In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
%matplotlib inline

df = pd.read_excel('data.xlsx')
df.rename(columns=df.iloc[0], inplace=True)
df = df.drop(df.index[0])
df = df.dropna(subset=['label'])
df = df.dropna(axis=1)
df = df.drop(columns=['번호','날짜','시간','시편상태','요약','수막두께'])
df = df.apply(pd.to_numeric)
df.columns

X = df.drop('label',axis=1).values
y = df['label'].values

from sklearn.model_selection import train_test_split


TypeError: train_test_split() got an unexpected keyword argument 'startify'

In [2]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=101)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [4]:
######## LogisticRegression ########

from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)
predictions_1 = logmodel.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, predictions_1))
print(classification_report(y_test, predictions_1))

[[4401  279]
 [ 475 6548]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92      4680
           1       0.96      0.93      0.95      7023

    accuracy                           0.94     11703
   macro avg       0.93      0.94      0.93     11703
weighted avg       0.94      0.94      0.94     11703



C:\Users\strai\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
##### Support Vector Machine #####

from sklearn.svm import SVC
svc_model = SVC()
svc_model.fit(X_train,y_train)

predictions_2 = svc_model.predict(X_test)
print(confusion_matrix(y_test, predictions_2))
print(classification_report(y_test, predictions_2))

[[4499  181]
 [ 355 6668]]
              precision    recall  f1-score   support

           0       0.93      0.96      0.94      4680
           1       0.97      0.95      0.96      7023

    accuracy                           0.95     11703
   macro avg       0.95      0.96      0.95     11703
weighted avg       0.95      0.95      0.95     11703



In [6]:
##### SGD Classifier #####

from sklearn.linear_model import SGDClassifier

sc=SGDClassifier(loss='log',max_iter=100,random_state=42)
sc.fit(X_train,y_train)
classes=np.unique(y_train)

for _ in range(0,300):
    sc.partial_fit(X_train,y_train,classes=classes)
predictions_3 = sc.predict(X_test)

print(confusion_matrix(y_test, predictions_3))
print(classification_report(y_test, predictions_3))

[[4317  363]
 [ 471 6552]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91      4680
           1       0.95      0.93      0.94      7023

    accuracy                           0.93     11703
   macro avg       0.92      0.93      0.93     11703
weighted avg       0.93      0.93      0.93     11703



In [9]:
##### Ensemble Hard Voting #####

predictions=[]

for i in range(len(predictions_1)):
    if (((predictions_1[i]) + (predictions_2[i]) + (predictions_3[i]))>=1):
        predictions.append(1)
    else: predictions.append(0)

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[4268  412]
 [ 310 6713]]
              precision    recall  f1-score   support

           0       0.93      0.91      0.92      4680
           1       0.94      0.96      0.95      7023

    accuracy                           0.94     11703
   macro avg       0.94      0.93      0.94     11703
weighted avg       0.94      0.94      0.94     11703

